name: Release unstable version

on:
  push:
    branches:
      - master

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: latest

      - name: Setup Nodejs
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: pnpm
          registry-url: https://registry.npmjs.org

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build
        run: pnpm run build

      - name: Commit and Push to pkg branch
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'
          git fetch origin pkg || git checkout -b pkg
          cp -r dist node_modules/dist
          git checkout pkg
          git checkout master -- LICENSE README.md package.json
          rm -rf dist && cp -r node_modules/dist ./
          pnpm version "$(pnpm pkg get version | tr -d '"')-$(echo ${{ github.sha }} | cut -c1-7)" --no-git-tag-version
          git add .
          if ! git diff --staged --quiet; then
            git commit -m "build: ${{ github.sha }}"
          fi
          git push origin pkg
